CREATE TABLE public.homeowner_projects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  homeowner_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  address text NOT NULL,
  zip_code text NOT NULL,
  jurisdiction_id uuid REFERENCES jurisdictions(id),
  project_type text NOT NULL CHECK (project_type IN ('adu_detached','adu_attached','jadu','addition','remodel','new_construction','conversion')),
  description text,
  ai_scope_summary text,
  ai_permit_checklist jsonb,
  ai_cost_estimate_low integer,
  ai_cost_estimate_high integer,
  ai_timeline_weeks_low integer,
  ai_timeline_weeks_high integer,
  ai_feasibility_notes text,
  ai_generated_at timestamptz,
  regrid_parcel_id text,
  lot_size_sqft integer,
  existing_sqft integer,
  year_built integer,
  zoning text,
  zoning_description text,
  parcel_geometry jsonb,
  fire_west_of_280 boolean DEFAULT false,
  fire_sprinklers_exist boolean DEFAULT false,
  has_earthwork boolean DEFAULT false,
  status text CHECK (status IN ('draft','ai_processing','scope_ready','posted_to_marketplace','contractor_selected','permit_in_progress','permitted','construction','complete','cancelled')) DEFAULT 'draft',
  map_lat numeric(10,7),
  map_lng numeric(10,7),
  map_heading numeric(6,2) DEFAULT 0,
  map_tilt numeric(5,2) DEFAULT 60,
  map_altitude numeric(8,2) DEFAULT 150,
  contractor_project_id uuid REFERENCES projects(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.homeowner_projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Homeowners manage own projects" ON homeowner_projects FOR ALL USING (auth.uid() = homeowner_id);
CREATE POLICY "Contractors view posted projects" ON homeowner_projects FOR SELECT USING (status = 'posted_to_marketplace' AND auth.role() = 'authenticated');